"""add_auth_jobs_modules

Revision ID: 68780b68b9ed
Revises: 001
Create Date: 2026-03-27 19:00:47.254096
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68780b68b9ed'
down_revision: Union[str, None] = '001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('remote', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=512), nullable=True),
    sa.Column('match_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('discovered', 'bookmarked', 'applied', 'interviewing', 'offered', 'accepted', 'rejected', 'skipped', name='job_status'), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('pipeline_runs', sa.Column('pipeline_type', sa.String(length=50), nullable=True))
    op.add_column('pipeline_runs', sa.Column('jobs_found', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('selected_modules', sa.JSON(), nullable=True, server_default='["leads","gigs","jobs"]'))
    op.execute("UPDATE users SET selected_modules = '[\"leads\",\"gigs\",\"jobs\"]' WHERE selected_modules IS NULL")
    op.alter_column('users', 'selected_modules', nullable=False)
    op.add_column('users', sa.Column('onboarding_completed', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('onboarding_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'onboarding_data')
    op.drop_column('users', 'onboarding_completed')
    op.drop_column('users', 'selected_modules')
    op.drop_column('users', 'password_hash')
    op.drop_column('pipeline_runs', 'jobs_found')
    op.drop_column('pipeline_runs', 'pipeline_type')
    op.drop_table('jobs')
    # ### end Alembic commands ###
