"""Realistic mock data for leads and gigs used by MCP tools."""

MOCK_LEADS = [
    {
        "name": "Sarah Chen",
        "company": "NovaTech Solutions",
        "role": "VP of Engineering",
        "email": "sarah.chen@novatech.io",
        "linkedin_url": "https://linkedin.com/in/sarachen-eng",
        "industry": "SaaS",
    },
    {
        "name": "Marcus Johnson",
        "company": "DataPipe Analytics",
        "role": "CTO",
        "email": "marcus@datapipe.com",
        "linkedin_url": "https://linkedin.com/in/marcusjohnson",
        "industry": "Data Analytics",
    },
    {
        "name": "Priya Patel",
        "company": "HealthBridge AI",
        "role": "Head of Product",
        "email": "priya.patel@healthbridge.ai",
        "linkedin_url": "https://linkedin.com/in/priyapatel-pm",
        "industry": "HealthTech",
    },
    {
        "name": "James O'Brien",
        "company": "FinEdge Capital",
        "role": "Director of Technology",
        "email": "jobrien@finedge.com",
        "linkedin_url": "https://linkedin.com/in/jamesobrien-tech",
        "industry": "FinTech",
    },
    {
        "name": "Aisha Rahman",
        "company": "EduSpark Labs",
        "role": "Founder & CEO",
        "email": "aisha@eduspark.io",
        "linkedin_url": "https://linkedin.com/in/aisharahman",
        "industry": "EdTech",
    },
    {
        "name": "David Kim",
        "company": "CloudNest Infrastructure",
        "role": "Engineering Manager",
        "email": "dkim@cloudnest.dev",
        "linkedin_url": "https://linkedin.com/in/davidkim-infra",
        "industry": "Cloud Infrastructure",
    },
    {
        "name": "Laura Martinez",
        "company": "RetailFlow",
        "role": "VP of Digital",
        "email": "laura.m@retailflow.com",
        "linkedin_url": "https://linkedin.com/in/lauramartinez-digital",
        "industry": "E-commerce",
    },
    {
        "name": "Tom Nakamura",
        "company": "CyberVault Security",
        "role": "CISO",
        "email": "tnakamura@cybervault.io",
        "linkedin_url": "https://linkedin.com/in/tomnakamura-sec",
        "industry": "Cybersecurity",
    },
    {
        "name": "Elena Volkov",
        "company": "GreenGrid Energy",
        "role": "Head of Software",
        "email": "elena.v@greengrid.tech",
        "linkedin_url": "https://linkedin.com/in/elenavolkov",
        "industry": "CleanTech",
    },
    {
        "name": "Ryan Brooks",
        "company": "MediaPulse",
        "role": "Technical Director",
        "email": "rbrooks@mediapulse.co",
        "linkedin_url": "https://linkedin.com/in/ryanbrooks-media",
        "industry": "Media & Entertainment",
    },
    {
        "name": "Fatima Al-Rashid",
        "company": "LogiChain Systems",
        "role": "COO",
        "email": "fatima@logichain.com",
        "linkedin_url": "https://linkedin.com/in/fatimaalrashid",
        "industry": "Supply Chain",
    },
    {
        "name": "Chris Andersson",
        "company": "PropTech Ventures",
        "role": "CTO",
        "email": "chris@proptechv.com",
        "linkedin_url": "https://linkedin.com/in/chrisandersson",
        "industry": "Real Estate Tech",
    },
]

MOCK_GIGS = [
    {
        "title": "Build AI-Powered Customer Support Chatbot",
        "platform": "upwork",
        "budget": 8000.0,
        "description": "We need an experienced developer to build an AI chatbot using LLMs for our SaaS platform. Must integrate with our existing ticketing system (Zendesk) and handle 500+ daily conversations. Looking for someone with NLP and API integration experience.",
        "url": "https://upwork.com/jobs/~01abc123",
        "deadline_days": 30,
        "skills_required": ["Python", "LLM", "API Integration", "NLP", "Chatbots"],
    },
    {
        "title": "Full-Stack Developer for FinTech Dashboard",
        "platform": "upwork",
        "budget": 12000.0,
        "description": "Seeking a full-stack developer to build a real-time trading dashboard. Stack: React, Node.js, PostgreSQL, WebSocket. Must have experience with financial data visualization and high-frequency data updates.",
        "url": "https://upwork.com/jobs/~01def456",
        "deadline_days": 45,
        "skills_required": ["React", "Node.js", "PostgreSQL", "WebSocket", "FinTech"],
    },
    {
        "title": "Data Pipeline Engineer — ETL Modernization",
        "platform": "linkedin",
        "budget": 15000.0,
        "description": "Migrate legacy batch ETL jobs to a modern streaming architecture using Apache Kafka, dbt, and Snowflake. Current system processes 10M records/day. Need someone who can design the architecture and implement the first 3 pipelines.",
        "url": "https://linkedin.com/jobs/view/123456",
        "deadline_days": 60,
        "skills_required": ["Python", "Kafka", "dbt", "Snowflake", "ETL"],
    },
    {
        "title": "Mobile App Backend API (FastAPI + PostgreSQL)",
        "platform": "upwork",
        "budget": 6000.0,
        "description": "Build a RESTful API backend for a fitness tracking mobile app. Features: user auth (JWT), workout logging, social features, push notifications. Must be production-ready with tests and Docker deployment.",
        "url": "https://upwork.com/jobs/~01ghi789",
        "deadline_days": 21,
        "skills_required": ["FastAPI", "PostgreSQL", "Docker", "JWT", "REST API"],
    },
    {
        "title": "Machine Learning Model for Fraud Detection",
        "platform": "linkedin",
        "budget": 20000.0,
        "description": "Develop and deploy an ML model for real-time transaction fraud detection. Must handle 1000 TPS with <100ms latency. Experience with scikit-learn, XGBoost, and model serving (FastAPI or TensorFlow Serving) required.",
        "url": "https://linkedin.com/jobs/view/234567",
        "deadline_days": 90,
        "skills_required": ["Python", "Machine Learning", "XGBoost", "FastAPI", "MLOps"],
    },
    {
        "title": "WordPress to Next.js Migration",
        "platform": "upwork",
        "budget": 5000.0,
        "description": "Migrate a 200-page WordPress site to Next.js with a headless CMS (Sanity or Contentful). Must preserve SEO rankings, implement ISR, and set up Vercel deployment. Current monthly traffic: 50k visits.",
        "url": "https://upwork.com/jobs/~01jkl012",
        "deadline_days": 28,
        "skills_required": ["Next.js", "React", "Headless CMS", "SEO", "Vercel"],
    },
    {
        "title": "DevOps Engineer — Kubernetes Cluster Setup",
        "platform": "freelancer",
        "budget": 10000.0,
        "description": "Set up a production Kubernetes cluster on AWS (EKS) with CI/CD (GitHub Actions), monitoring (Prometheus + Grafana), and auto-scaling. Must include IaC using Terraform.",
        "url": "https://freelancer.com/projects/devops-k8s-345",
        "deadline_days": 35,
        "skills_required": ["Kubernetes", "AWS", "Terraform", "CI/CD", "DevOps"],
    },
    {
        "title": "E-commerce Platform — Shopify Custom App",
        "platform": "upwork",
        "budget": 7500.0,
        "description": "Build a custom Shopify app for inventory sync across multiple warehouses. Must use Shopify Admin API, handle webhooks for order events, and provide a merchant-facing React dashboard.",
        "url": "https://upwork.com/jobs/~01mno345",
        "deadline_days": 25,
        "skills_required": ["Shopify", "React", "Node.js", "Webhooks", "E-commerce"],
    },
    {
        "title": "AI Content Generation Tool",
        "platform": "linkedin",
        "budget": 9000.0,
        "description": "Build a content generation tool using Claude/GPT APIs. Features: blog post generation, social media copy, SEO optimization suggestions. Need a clean UI (Next.js) and robust prompt engineering.",
        "url": "https://linkedin.com/jobs/view/345678",
        "deadline_days": 40,
        "skills_required": ["Python", "LLM", "Next.js", "Prompt Engineering", "API"],
    },
    {
        "title": "React Native App for Healthcare Startup",
        "platform": "upwork",
        "budget": 14000.0,
        "description": "Develop a cross-platform mobile app for patient appointment scheduling and telemedicine. Must be HIPAA-compliant, integrate with Twilio Video, and support offline mode.",
        "url": "https://upwork.com/jobs/~01pqr678",
        "deadline_days": 60,
        "skills_required": ["React Native", "Healthcare", "Twilio", "HIPAA", "Mobile"],
    },
    {
        "title": "Automated Testing Framework Setup",
        "platform": "freelancer",
        "budget": 4000.0,
        "description": "Set up an end-to-end testing framework for our web application using Playwright. Write tests for 20 critical user flows, integrate with GitHub Actions CI, and create a test reporting dashboard.",
        "url": "https://freelancer.com/projects/testing-auto-456",
        "deadline_days": 14,
        "skills_required": ["Playwright", "Testing", "CI/CD", "JavaScript", "QA"],
    },
    {
        "title": "Blockchain Smart Contract Audit",
        "platform": "linkedin",
        "budget": 18000.0,
        "description": "Audit Solidity smart contracts for a DeFi lending protocol. Review 5 contracts (~3000 lines total), produce a detailed security report, and verify fixes. Must have prior audit experience.",
        "url": "https://linkedin.com/jobs/view/456789",
        "deadline_days": 21,
        "skills_required": ["Solidity", "Smart Contracts", "Security", "DeFi", "Blockchain"],
    },
]
